replicaCount: 1

image:
  repository: ghcr.io/appuio/maxscale-docker
  tag: 6.4.6  # pick a stable version

service:
  type: ClusterIP
  port: 3306

config:
  maxscale.cnf: |
    [maxscale]
    threads=auto

    # Monitor section
    [MariaDB-Monitor]
    type=monitor
    module=mariadbmon
    servers=server1,server2
    user=maxscale_monitor
    password=StrongPass123!
    monitor_interval=2000ms
    auto_failover=true
    auto_rejoin=true
    failcount=3
    enforce_read_only_slaves=true

    # Define servers (adjust hostnames and ports)
    [server1]
    type=server
    address=mariadb-master.pp-playground.svc.cluster.local
    port=3306
    protocol=MariaDBBackend

    [server2]
    type=server
    address=mariadb-replica.pp-playground.svc.cluster.local
    port=3306
    protocol=MariaDBBackend

    # Write to primary only
    [Write-Service]
    type=service
    router=readwritesplit
    servers=server1,server2
    user=maxscale_monitor
    password=StrongPass123!
    max_slave_connections=100%

    [Write-Listener]
    type=listener
    service=Write-Service
    protocol=MariaDBClient
    port=3306

extraEnvFrom:
  - secretRef:
      name: maxscale-monitor-secret